"""empty message

Revision ID: ae1f0cfcb87b
Revises: 
Create Date: 2024-04-18 15:13:00.563050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae1f0cfcb87b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserDetails',
    sa.Column('USER_ID', sa.Integer(), nullable=False),
    sa.Column('USER_NAME', sa.String(length=250), nullable=False),
    sa.Column('PASSWORD', sa.String(length=250), nullable=False),
    sa.Column('FIRST_NAME', sa.String(length=250), nullable=False),
    sa.Column('MIDDLE_NAME', sa.String(length=250), nullable=True),
    sa.Column('MOBILE_NO', sa.BigInteger(), nullable=True),
    sa.Column('LAST_NAME', sa.String(length=250), nullable=False),
    sa.Column('EMAIL', sa.String(length=250), nullable=True),
    sa.Column('USER_TYPE', sa.String(length=250), nullable=False),
    sa.Column('CREATED_BY', sa.String(length=250), nullable=False),
    sa.Column('LAST_UPDATED_BY', sa.String(length=250), nullable=False),
    sa.Column('CREATION_AT', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_AT', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('USER_ID'),
    sa.UniqueConstraint('EMAIL'),
    sa.UniqueConstraint('MOBILE_NO')
    )
    op.create_table('emp_detalies',
    sa.Column('EMPLOYEE_NUMBER', sa.Integer(), nullable=False),
    sa.Column('FIRST_NAME', sa.String(length=225), nullable=False),
    sa.Column('LAST_NAME', sa.String(length=225), nullable=False),
    sa.Column('DATE_OF_BIRTH', sa.Date(), nullable=True),
    sa.Column('LOCATION', sa.String(length=225), nullable=False),
    sa.Column('EMAIL', sa.String(length=225), nullable=False),
    sa.Column('CREATION_DATE', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_DATE', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('EMPLOYEE_NUMBER'),
    sa.UniqueConstraint('EMAIL')
    )
    op.create_table('letter_templates',
    sa.Column('TEMPLATE_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('TEMPLATE_NAME', sa.String(length=225), nullable=False),
    sa.Column('TEMPLATE', sa.LargeBinary(length=10485760), nullable=True),
    sa.Column('FILE_SIZE', sa.Integer(), nullable=True),
    sa.Column('TEMPLATE_TYPE', sa.String(length=225), nullable=False),
    sa.Column('CREATED_BY', sa.String(length=225), nullable=False),
    sa.Column('LAST_UPDATED_BY', sa.String(length=225), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_AT', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('TEMPLATE_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('letter_templates')
    op.drop_table('emp_detalies')
    op.drop_table('UserDetails')
    # ### end Alembic commands ###
