"""empty message

Revision ID: db4cfee6f9e6
Revises: 
Create Date: 2024-04-24 17:31:26.066959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4cfee6f9e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('letter_templates',
    sa.Column('TEMPLATE_ID', sa.String(length=225), nullable=False),
    sa.Column('TEMPLATE_NAME', sa.String(length=225), nullable=False),
    sa.Column('TEMPLATE', sa.LargeBinary(length=10485760), nullable=True),
    sa.Column('FILE_SIZE', sa.Integer(), nullable=True),
    sa.Column('TEMPLATE_TYPE', sa.String(length=225), nullable=False),
    sa.Column('CREATED_BY', sa.String(length=225), nullable=False),
    sa.Column('LAST_UPDATED_BY', sa.String(length=225), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_AT', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('TEMPLATE_ID')
    )
    op.create_table('userdetails',
    sa.Column('USER_ID', sa.Integer(), nullable=False),
    sa.Column('USER_NAME', sa.String(length=250), nullable=False),
    sa.Column('PASSWORD', sa.String(length=250), nullable=False),
    sa.Column('FIRST_NAME', sa.String(length=250), nullable=False),
    sa.Column('MIDDLE_NAME', sa.String(length=250), nullable=True),
    sa.Column('MOBILE_NO', sa.BigInteger(), nullable=True),
    sa.Column('LAST_NAME', sa.String(length=250), nullable=False),
    sa.Column('EMAIL', sa.String(length=250), nullable=True),
    sa.Column('USER_TYPE', sa.String(length=250), nullable=False),
    sa.Column('CREATED_BY', sa.String(length=250), nullable=False),
    sa.Column('LAST_UPDATED_BY', sa.String(length=250), nullable=False),
    sa.Column('CREATION_AT', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_AT', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('USER_ID'),
    sa.UniqueConstraint('EMAIL'),
    sa.UniqueConstraint('MOBILE_NO')
    )
    op.create_table('employee_details',
    sa.Column('EMP_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('EMP_NO', sa.String(length=225), nullable=False),
    sa.Column('FIRST_NAME', sa.String(length=225), nullable=False),
    sa.Column('MIDDLE_NAME', sa.String(length=225), nullable=True),
    sa.Column('LAST_NAME', sa.String(length=225), nullable=False),
    sa.Column('EMAIL_ADDRESS', sa.String(length=225), nullable=True),
    sa.Column('DATE_OF_JOINING', sa.Date(), nullable=False),
    sa.Column('DATE_OF_BIRTH', sa.Date(), nullable=False),
    sa.Column('WORK_LOCATION', sa.String(length=225), nullable=False),
    sa.Column('USER_ID', sa.Integer(), nullable=True),
    sa.Column('EFFECTIVE_START_DATE', sa.DateTime(), nullable=False),
    sa.Column('EFFECTIVE_END_DATE', sa.DateTime(), nullable=True),
    sa.Column('WORKER_TYPE', sa.String(length=225), nullable=False),
    sa.Column('CREATED_BY', sa.String(length=225), nullable=False),
    sa.Column('LAST_UPDATED_BY', sa.String(length=225), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_AT', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['USER_ID'], ['userdetails.USER_ID'], ),
    sa.PrimaryKeyConstraint('EMP_ID')
    )
    op.create_table('emp_letters',
    sa.Column('LETTER_ID', sa.Integer(), nullable=False),
    sa.Column('EMP_ID', sa.Integer(), nullable=True),
    sa.Column('TEMPLATE_ID', sa.String(length=225), nullable=True),
    sa.Column('LETTER_TYPE', sa.String(length=50), nullable=False),
    sa.Column('LETTER', sa.LargeBinary(length=10485760), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=50), nullable=False),
    sa.Column('LAST_UPDATED_BY', sa.String(length=50), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_AT', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['EMP_ID'], ['employee_details.EMP_ID'], ),
    sa.ForeignKeyConstraint(['TEMPLATE_ID'], ['letter_templates.TEMPLATE_ID'], ),
    sa.PrimaryKeyConstraint('LETTER_ID')
    )
    op.create_table('employee_address_details',
    sa.Column('ADDRESS_ID', sa.Integer(), nullable=False),
    sa.Column('EMP_ID', sa.Integer(), nullable=True),
    sa.Column('ADDRESS_TYPE', sa.String(length=225), nullable=False),
    sa.Column('ADDRESS', sa.String(length=225), nullable=False),
    sa.Column('CITY', sa.String(length=225), nullable=False),
    sa.Column('STATE', sa.String(length=225), nullable=False),
    sa.Column('COUNTRY', sa.String(length=225), nullable=False),
    sa.Column('PIN_CODE', sa.Integer(), nullable=False),
    sa.Column('DATE_FROM', sa.TIMESTAMP(), nullable=True),
    sa.Column('DATE_TO', sa.TIMESTAMP(), nullable=True),
    sa.Column('PHONE_1', sa.String(length=225), nullable=True),
    sa.Column('PHONE_2', sa.String(length=225), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=225), nullable=False),
    sa.Column('LAST_UPDATED_BY', sa.String(length=225), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_AT', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['EMP_ID'], ['employee_details.EMP_ID'], ),
    sa.PrimaryKeyConstraint('ADDRESS_ID')
    )
    op.create_table('employment_details',
    sa.Column('ASSIGNMENT_ID', sa.Integer(), nullable=False),
    sa.Column('ORGANIZATION_NAME', sa.String(length=225), nullable=False),
    sa.Column('POSITION', sa.String(length=225), nullable=False),
    sa.Column('DEPARTMENT', sa.String(length=225), nullable=False),
    sa.Column('ANNUAL_SALARY', sa.Float(), nullable=True),
    sa.Column('PREVIOUS_ANNUAL_SALARY', sa.Float(), nullable=True),
    sa.Column('EMAIL', sa.String(length=225), nullable=True),
    sa.Column('WORK_LOCATION', sa.String(length=225), nullable=False),
    sa.Column('MOBILE_NO', sa.BigInteger(), nullable=False),
    sa.Column('PROBATION_PERIOD', sa.Integer(), nullable=True),
    sa.Column('NOTICE_PERIOD', sa.Integer(), nullable=True),
    sa.Column('CONFIRMATION_DATE', sa.Date(), nullable=True),
    sa.Column('EFFECTIVE_START_DATE', sa.TIMESTAMP(), nullable=True),
    sa.Column('EFFECTIVE_END_DATE', sa.DateTime(), nullable=True),
    sa.Column('EMP_ID', sa.Integer(), nullable=True),
    sa.Column('CREATED_BY', sa.String(length=225), nullable=False),
    sa.Column('LAST_UPDATED_BY', sa.String(length=225), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False),
    sa.Column('LAST_UPDATED_AT', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['EMP_ID'], ['employee_details.EMP_ID'], ),
    sa.PrimaryKeyConstraint('ASSIGNMENT_ID'),
    sa.UniqueConstraint('EMAIL')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employment_details')
    op.drop_table('employee_address_details')
    op.drop_table('emp_letters')
    op.drop_table('employee_details')
    op.drop_table('userdetails')
    op.drop_table('letter_templates')
    # ### end Alembic commands ###
